"""initial migration

Revision ID: 49911e3b43cf
Revises: 
Create Date: 2026-03-10 21:39:24.375287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49911e3b43cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('First_Name', sa.String(length=10), nullable=False),
    sa.Column('Last_Name', sa.String(length=10), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('Role', sa.Enum('Engineer', 'Manager'), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('Bugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bug_code', sa.String(length=50), nullable=False),
    sa.Column('bug_type', sa.Enum('repro', 'test'), nullable=False),
    sa.Column('engineer_id', sa.Integer(), nullable=True),
    sa.Column('station_config', sa.String(length=100), nullable=True),
    sa.Column('resource_group', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'scheduled', 'completed'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['engineer_id'], ['Users.ID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bug_code')
    )
    op.create_table('Workgroup_Schema',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=True),
    sa.Column('Release_Version', sa.String(length=10), nullable=False),
    sa.Column('Status', sa.Enum('Completed', 'Active'), server_default='Active', nullable=False),
    sa.Column('Manager_ID', sa.Integer(), nullable=True),
    sa.Column('Created_At', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['Manager_ID'], ['Users.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('Bug_Tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bug_id', sa.Integer(), nullable=True),
    sa.Column('test_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['bug_id'], ['Bugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Bug_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bug_id', sa.Integer(), nullable=True),
    sa.Column('station_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['bug_id'], ['Bugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Workgroup_Assignment_Schema',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Workgroup_ID', sa.Integer(), nullable=False),
    sa.Column('Employee_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Employee_ID'], ['Users.ID'], ),
    sa.ForeignKeyConstraint(['Workgroup_ID'], ['Workgroup_Schema.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.drop_table('workgroup_schema')
    op.drop_table('workgroup_assignment_schema')
    with op.batch_alter_table('bugs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('bug_code'))

    op.drop_table('bugs')
    op.drop_table('bug_stations')
    op.drop_table('bug_tests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('Email'))

    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('First_Name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=False),
    sa.Column('Last_Name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('Email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('Password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('Role', mysql.ENUM('Engineer', 'Manager'), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('Email'), ['Email'], unique=True)

    op.create_table('bug_tests',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bug_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('test_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.id'], name=op.f('bug_tests_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('bug_stations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bug_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('station_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.id'], name=op.f('bug_stations_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('bugs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bug_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('bug_type', mysql.ENUM('repro', 'test'), nullable=False),
    sa.Column('engineer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('station_config', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('resource_group', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('status', mysql.ENUM('pending', 'running', 'scheduled', 'completed'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['engineer_id'], ['users.ID'], name=op.f('bugs_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('bugs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('bug_code'), ['bug_code'], unique=True)

    op.create_table('workgroup_assignment_schema',
    sa.Column('ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Workgroup_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Employee_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Employee_ID'], ['users.ID'], name=op.f('workgroup_assignment_schema_ibfk_2')),
    sa.ForeignKeyConstraint(['Workgroup_ID'], ['workgroup_schema.ID'], name=op.f('workgroup_assignment_schema_ibfk_1')),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('workgroup_schema',
    sa.Column('ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('Release_Version', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=False),
    sa.Column('Status', mysql.ENUM('Completed', 'Active'), server_default=sa.text("'Active'"), nullable=False),
    sa.Column('Manager_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Created_At', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['Manager_ID'], ['users.ID'], name=op.f('workgroup_schema_ibfk_1')),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Workgroup_Assignment_Schema')
    op.drop_table('Bug_stations')
    op.drop_table('Bug_Tests')
    op.drop_table('Workgroup_Schema')
    op.drop_table('Bugs')
    op.drop_table('Users')
    # ### end Alembic commands ###
